import {
  blue,
  blueDark,
  red,
  redDark,
  amber,
  amberDark,
  green,
  greenDark,
  orange,
  orangeDark,
  purple,
  purpleDark,
  pink,
  pinkDark,
  slate,
  slateDark,
} from '@radix-ui/colors';

export const palette = {
  white: 'hsl(0, 0%, 100%)',
  black: 'hsl(0, 0%, 0%)',
  light: {
    ...blue,
    ...red,
    ...green,
    ...orange,
    ...purple,
    ...pink,
    yellow1: amber.amber1,
    yellow2: amber.amber2,
    yellow3: amber.amber3,
    yellow4: amber.amber4,
    yellow5: amber.amber5,
    yellow6: amber.amber6,
    yellow7: amber.amber7,
    yellow8: amber.amber8,
    yellow9: amber.amber9,
    yellow10: amber.amber10,
    yellow11: amber.amber11,
    yellow12: amber.amber12,
    gray1: slate.slate1,
    gray2: slate.slate2,
    gray3: slate.slate3,
    gray4: slate.slate4,
    gray5: slate.slate5,
    gray6: slate.slate6,
    gray7: slate.slate7,
    gray8: slate.slate8,
    gray9: slate.slate9,
    gray10: slate.slate10,
    gray11: slate.slate11,
    gray12: slate.slate12,
  },
  dark: {
    ...blueDark,
    ...redDark,
    ...greenDark,
    ...orangeDark,
    ...purpleDark,
    ...pinkDark,
    yellow1: amberDark.amber1,
    yellow2: amberDark.amber2,
    yellow3: amberDark.amber3,
    yellow4: amberDark.amber4,
    yellow5: amberDark.amber5,
    yellow6: amberDark.amber6,
    yellow7: amberDark.amber7,
    yellow8: amberDark.amber8,
    yellow9: amberDark.amber9,
    yellow10: amberDark.amber10,
    yellow11: amberDark.amber11,
    yellow12: amberDark.amber12,
    gray1: slateDark.slate1,
    gray2: slateDark.slate2,
    gray3: slateDark.slate3,
    gray4: slateDark.slate4,
    gray5: slateDark.slate5,
    gray6: slateDark.slate6,
    gray7: slateDark.slate7,
    gray8: slateDark.slate8,
    gray9: slateDark.slate9,
    gray10: slateDark.slate10,
    gray11: slateDark.slate11,
    gray12: slateDark.slate12,
  },
};
