export const theme = {
  background: {
    default: 'var(--expo-color-theme-background-default)',
    canvas: 'var(--expo-color-theme-background-canvas)',
    secondary: 'var(--expo-color-theme-background-secondary)',
    tertiary: 'var(--expo-color-theme-background-tertiary)',
    quaternary: 'var(--expo-color-theme-background-quaternary)',
    error: 'var(--expo-color-theme-background-error)',
    warning: 'var(--expo-color-theme-background-warning)',
    success: 'var(--expo-color-theme-background-success)',
  },
  border: {
    default: 'var(--expo-color-theme-border-default)',
    error: 'var(--expo-color-theme-border-error)',
    warning: 'var(--expo-color-theme-border-warning)',
    success: 'var(--expo-color-theme-border-success)',
  },
  button: {
    primary: 'var(--expo-color-theme-button-primary)',
    secondary: 'var(--expo-color-theme-button-secondary)',
    tertiary: 'var(--expo-color-theme-button-tertiary)',
  },
  link: { default: 'var(--expo-color-theme-link-default)' },
  status: {
    default: 'var(--expo-color-theme-status-default)',
    error: 'var(--expo-color-theme-status-error)',
    warning: 'var(--expo-color-theme-status-warning)',
    success: 'var(--expo-color-theme-status-success)',
    info: 'var(--expo-color-theme-status-info)',
  },
  text: {
    default: 'var(--expo-color-theme-text-default)',
    secondary: 'var(--expo-color-theme-text-secondary)',
    error: 'var(--expo-color-theme-text-error)',
    warning: 'var(--expo-color-theme-text-warning)',
    success: 'var(--expo-color-theme-text-success)',
  },
  icon: { default: 'var(--expo-color-theme-icon-default)' },
  code: {
    keyword: 'var(--expo-color-theme-code-keyword)',
    builtin: 'var(--expo-color-theme-code-builtin)',
    property: 'var(--expo-color-theme-code-property)',
    comment: 'var(--expo-color-theme-code-comment)',
    punctuation: 'var(--expo-color-theme-code-punctuation)',
    operator: 'var(--expo-color-theme-code-operator)',
    regex: 'var(--expo-color-theme-code-regex)',
    string: 'var(--expo-color-theme-code-string)',
    before: 'var(--expo-color-theme-code-before)',
  },
  highlight: {
    accent: 'var(--expo-color-theme-highlight-accent)',
    emphasis: 'var(--expo-color-theme-highlight-emphasis)',
  },
};

export const colors = {
  light: {
    gray: {
      100: 'var(--expo-color-base-light-gray-100)',
      200: 'var(--expo-color-base-light-gray-200)',
      300: 'var(--expo-color-base-light-gray-300)',
      400: 'var(--expo-color-base-light-gray-400)',
      500: 'var(--expo-color-base-light-gray-500)',
      600: 'var(--expo-color-base-light-gray-600)',
      700: 'var(--expo-color-base-light-gray-700)',
      800: 'var(--expo-color-base-light-gray-800)',
      900: 'var(--expo-color-base-light-gray-900)',
      1000: 'var(--expo-color-base-light-gray-1000)',
      '000': 'var(--expo-color-base-light-gray-000)',
    },
    primary: {
      100: 'var(--expo-color-base-light-primary-100)',
      200: 'var(--expo-color-base-light-primary-200)',
      300: 'var(--expo-color-base-light-primary-300)',
      400: 'var(--expo-color-base-light-primary-400)',
      500: 'var(--expo-color-base-light-primary-500)',
      600: 'var(--expo-color-base-light-primary-600)',
      700: 'var(--expo-color-base-light-primary-700)',
      800: 'var(--expo-color-base-light-primary-800)',
      900: 'var(--expo-color-base-light-primary-900)',
      '000': 'var(--expo-color-base-light-primary-000)',
    },
    blue: {
      100: 'var(--expo-color-base-light-blue-100)',
      200: 'var(--expo-color-base-light-blue-200)',
      300: 'var(--expo-color-base-light-blue-300)',
      400: 'var(--expo-color-base-light-blue-400)',
      500: 'var(--expo-color-base-light-blue-500)',
      600: 'var(--expo-color-base-light-blue-600)',
      700: 'var(--expo-color-base-light-blue-700)',
      800: 'var(--expo-color-base-light-blue-800)',
      900: 'var(--expo-color-base-light-blue-900)',
      '000': 'var(--expo-color-base-light-blue-000)',
    },
    green: {
      100: 'var(--expo-color-base-light-green-100)',
      200: 'var(--expo-color-base-light-green-200)',
      300: 'var(--expo-color-base-light-green-300)',
      400: 'var(--expo-color-base-light-green-400)',
      500: 'var(--expo-color-base-light-green-500)',
      600: 'var(--expo-color-base-light-green-600)',
      700: 'var(--expo-color-base-light-green-700)',
      800: 'var(--expo-color-base-light-green-800)',
      900: 'var(--expo-color-base-light-green-900)',
      '000': 'var(--expo-color-base-light-green-000)',
    },
    yellow: {
      100: 'var(--expo-color-base-light-yellow-100)',
      200: 'var(--expo-color-base-light-yellow-200)',
      300: 'var(--expo-color-base-light-yellow-300)',
      400: 'var(--expo-color-base-light-yellow-400)',
      500: 'var(--expo-color-base-light-yellow-500)',
      600: 'var(--expo-color-base-light-yellow-600)',
      700: 'var(--expo-color-base-light-yellow-700)',
      800: 'var(--expo-color-base-light-yellow-800)',
      900: 'var(--expo-color-base-light-yellow-900)',
      '000': 'var(--expo-color-base-light-yellow-000)',
    },
    orange: {
      100: 'var(--expo-color-base-light-orange-100)',
      200: 'var(--expo-color-base-light-orange-200)',
      300: 'var(--expo-color-base-light-orange-300)',
      400: 'var(--expo-color-base-light-orange-400)',
      500: 'var(--expo-color-base-light-orange-500)',
      600: 'var(--expo-color-base-light-orange-600)',
      700: 'var(--expo-color-base-light-orange-700)',
      800: 'var(--expo-color-base-light-orange-800)',
      900: 'var(--expo-color-base-light-orange-900)',
      '000': 'var(--expo-color-base-light-orange-000)',
    },
    red: {
      100: 'var(--expo-color-base-light-red-100)',
      200: 'var(--expo-color-base-light-red-200)',
      300: 'var(--expo-color-base-light-red-300)',
      400: 'var(--expo-color-base-light-red-400)',
      500: 'var(--expo-color-base-light-red-500)',
      600: 'var(--expo-color-base-light-red-600)',
      700: 'var(--expo-color-base-light-red-700)',
      800: 'var(--expo-color-base-light-red-800)',
      900: 'var(--expo-color-base-light-red-900)',
      '000': 'var(--expo-color-base-light-red-000)',
    },
    pink: {
      100: 'var(--expo-color-base-light-pink-100)',
      200: 'var(--expo-color-base-light-pink-200)',
      300: 'var(--expo-color-base-light-pink-300)',
      400: 'var(--expo-color-base-light-pink-400)',
      500: 'var(--expo-color-base-light-pink-500)',
      600: 'var(--expo-color-base-light-pink-600)',
      700: 'var(--expo-color-base-light-pink-700)',
      800: 'var(--expo-color-base-light-pink-800)',
      900: 'var(--expo-color-base-light-pink-900)',
      '000': 'var(--expo-color-base-light-pink-000)',
    },
    purple: {
      100: 'var(--expo-color-base-light-purple-100)',
      200: 'var(--expo-color-base-light-purple-200)',
      300: 'var(--expo-color-base-light-purple-300)',
      400: 'var(--expo-color-base-light-purple-400)',
      500: 'var(--expo-color-base-light-purple-500)',
      600: 'var(--expo-color-base-light-purple-600)',
      700: 'var(--expo-color-base-light-purple-700)',
      800: 'var(--expo-color-base-light-purple-800)',
      900: 'var(--expo-color-base-light-purple-900)',
      '000': 'var(--expo-color-base-light-purple-000)',
    },
    white: 'var(--expo-color-base-light-white)',
    black: 'var(--expo-color-base-light-black)',
  },
  dark: {
    gray: {
      100: 'var(--expo-color-base-dark-gray-100)',
      200: 'var(--expo-color-base-dark-gray-200)',
      300: 'var(--expo-color-base-dark-gray-300)',
      400: 'var(--expo-color-base-dark-gray-400)',
      500: 'var(--expo-color-base-dark-gray-500)',
      600: 'var(--expo-color-base-dark-gray-600)',
      700: 'var(--expo-color-base-dark-gray-700)',
      800: 'var(--expo-color-base-dark-gray-800)',
      900: 'var(--expo-color-base-dark-gray-900)',
      1000: 'var(--expo-color-base-dark-gray-1000)',
      '000': 'var(--expo-color-base-dark-gray-000)',
    },
    primary: {
      100: 'var(--expo-color-base-dark-primary-100)',
      200: 'var(--expo-color-base-dark-primary-200)',
      300: 'var(--expo-color-base-dark-primary-300)',
      400: 'var(--expo-color-base-dark-primary-400)',
      500: 'var(--expo-color-base-dark-primary-500)',
      600: 'var(--expo-color-base-dark-primary-600)',
      700: 'var(--expo-color-base-dark-primary-700)',
      800: 'var(--expo-color-base-dark-primary-800)',
      900: 'var(--expo-color-base-dark-primary-900)',
      '000': 'var(--expo-color-base-dark-primary-000)',
    },
    blue: {
      100: 'var(--expo-color-base-dark-blue-100)',
      200: 'var(--expo-color-base-dark-blue-200)',
      300: 'var(--expo-color-base-dark-blue-300)',
      400: 'var(--expo-color-base-dark-blue-400)',
      500: 'var(--expo-color-base-dark-blue-500)',
      600: 'var(--expo-color-base-dark-blue-600)',
      700: 'var(--expo-color-base-dark-blue-700)',
      800: 'var(--expo-color-base-dark-blue-800)',
      900: 'var(--expo-color-base-dark-blue-900)',
      '000': 'var(--expo-color-base-dark-blue-000)',
    },
    green: {
      100: 'var(--expo-color-base-dark-green-100)',
      200: 'var(--expo-color-base-dark-green-200)',
      300: 'var(--expo-color-base-dark-green-300)',
      400: 'var(--expo-color-base-dark-green-400)',
      500: 'var(--expo-color-base-dark-green-500)',
      600: 'var(--expo-color-base-dark-green-600)',
      700: 'var(--expo-color-base-dark-green-700)',
      800: 'var(--expo-color-base-dark-green-800)',
      900: 'var(--expo-color-base-dark-green-900)',
      '000': 'var(--expo-color-base-dark-green-000)',
    },
    yellow: {
      100: 'var(--expo-color-base-dark-yellow-100)',
      200: 'var(--expo-color-base-dark-yellow-200)',
      300: 'var(--expo-color-base-dark-yellow-300)',
      400: 'var(--expo-color-base-dark-yellow-400)',
      500: 'var(--expo-color-base-dark-yellow-500)',
      600: 'var(--expo-color-base-dark-yellow-600)',
      700: 'var(--expo-color-base-dark-yellow-700)',
      800: 'var(--expo-color-base-dark-yellow-800)',
      900: 'var(--expo-color-base-dark-yellow-900)',
      '000': 'var(--expo-color-base-dark-yellow-000)',
    },
    orange: {
      100: 'var(--expo-color-base-dark-orange-100)',
      200: 'var(--expo-color-base-dark-orange-200)',
      300: 'var(--expo-color-base-dark-orange-300)',
      400: 'var(--expo-color-base-dark-orange-400)',
      500: 'var(--expo-color-base-dark-orange-500)',
      600: 'var(--expo-color-base-dark-orange-600)',
      700: 'var(--expo-color-base-dark-orange-700)',
      800: 'var(--expo-color-base-dark-orange-800)',
      900: 'var(--expo-color-base-dark-orange-900)',
      '000': 'var(--expo-color-base-dark-orange-000)',
    },
    red: {
      100: 'var(--expo-color-base-dark-red-100)',
      200: 'var(--expo-color-base-dark-red-200)',
      300: 'var(--expo-color-base-dark-red-300)',
      400: 'var(--expo-color-base-dark-red-400)',
      500: 'var(--expo-color-base-dark-red-500)',
      600: 'var(--expo-color-base-dark-red-600)',
      700: 'var(--expo-color-base-dark-red-700)',
      800: 'var(--expo-color-base-dark-red-800)',
      900: 'var(--expo-color-base-dark-red-900)',
      '000': 'var(--expo-color-base-dark-red-000)',
    },
    pink: {
      100: 'var(--expo-color-base-dark-pink-100)',
      200: 'var(--expo-color-base-dark-pink-200)',
      300: 'var(--expo-color-base-dark-pink-300)',
      400: 'var(--expo-color-base-dark-pink-400)',
      500: 'var(--expo-color-base-dark-pink-500)',
      600: 'var(--expo-color-base-dark-pink-600)',
      700: 'var(--expo-color-base-dark-pink-700)',
      800: 'var(--expo-color-base-dark-pink-800)',
      900: 'var(--expo-color-base-dark-pink-900)',
      '000': 'var(--expo-color-base-dark-pink-000)',
    },
    purple: {
      100: 'var(--expo-color-base-dark-purple-100)',
      200: 'var(--expo-color-base-dark-purple-200)',
      300: 'var(--expo-color-base-dark-purple-300)',
      400: 'var(--expo-color-base-dark-purple-400)',
      500: 'var(--expo-color-base-dark-purple-500)',
      600: 'var(--expo-color-base-dark-purple-600)',
      700: 'var(--expo-color-base-dark-purple-700)',
      800: 'var(--expo-color-base-dark-purple-800)',
      900: 'var(--expo-color-base-dark-purple-900)',
      '000': 'var(--expo-color-base-dark-purple-000)',
    },
    white: 'var(--expo-color-base-dark-white)',
    black: 'var(--expo-color-base-dark-black)',
  },
};
