name: Check packages and deploy website

env:
  NODE_ENV: production
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  FILE_ID: zHeGLN45wIgf39kqdvKpoj

on:
  push:
    branches: [main]
    paths:
      - .github/workflows/deploy.yml
      - packages/**
  pull_request:
    paths:
      - .github/workflows/deploy.yml
      - packages/**

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: 👀 Checkout
        uses: actions/checkout@v4

      - name: ⬢ Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: 🧶 Yarn install
        run: yarn install --immutable

      - name: 🚨 Lint code
        run: yarn lint --max-warnings 0

      - name: 📦️ Build packages
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}
        run: yarn build

      - name: ⬇️️ Pull example-web metadata for preview
        if: github.ref != 'refs/heads/main'
        working-directory: packages/example-web
        run: yarn dlx vercel pull --token ${{ secrets.VERCEL_TOKEN }}
      - name: 📦️ Build example-app for preview
        if: github.ref != 'refs/heads/main'
        working-directory: packages/example-web
        run: yarn dlx vercel build --token ${{ secrets.VERCEL_TOKEN }}

      - name: ⬇️️ Pull example-web metadata
        if: github.ref == 'refs/heads/main'
        working-directory: packages/example-web
        run: yarn dlx vercel pull --token ${{ secrets.VERCEL_TOKEN }} --environment=production
      - name: 📦️ Build example-app
        if: github.ref == 'refs/heads/main'
        working-directory: packages/example-web
        run: yarn dlx vercel build --token ${{ secrets.VERCEL_TOKEN }} --prod

      - name: 🚀 Deploy website
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.EXPO_BOT_GH_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          PREBUILT: true
          WORKING_DIRECTORY: packages/example-web
